### ISSUE TITLE
Add that users can change the logo

### ISSUE THREAD

**Issue by Venni1** [Hellscaped/Syntax-Plus#2]
This should be great since some may want to change the logo. Like from settings, you can change the logo by inputting a URL that is the logo that the user wants. As I changed the logo to the classic Roblox logo from Tampermonkey, there should be an easier way to change the logo.

**Comment by thrailkillr** [comment]
> This should be great since some may want to change the logo. Like from settings, you can change the logo by inputting a URL that is the logo that the user wants. As I changed the logo to the classic Roblox logo from Tampermonkey, there should be an easier way to change the logo.

This is already on my TODO list
